/* Katalog ikon do pickera (emoji → SVG OpenMoji przez util.emo).
   Wpis: [emoji, nazwa PL, nazwa EN] — obie nazwy przeszukiwalne w combo. */

const C = [
  // warzywa
  ["🍅", "pomidor", "tomato"],
  ["🥕", "marchew", "carrot"],
  ["🥬", "sałata / kapusta liściowa", "lettuce / leafy greens"],
  ["🥒", "ogórek", "cucumber"],
  ["🌶️", "papryka ostra", "hot pepper"],
  ["🫑", "papryka", "bell pepper"],
  ["🍆", "bakłażan", "eggplant"],
  ["🥔", "ziemniak", "potato"],
  ["🍠", "batat", "sweet potato"],
  ["🧅", "cebula", "onion"],
  ["🧄", "czosnek", "garlic"],
  ["🥦", "brokuł", "broccoli"],
  ["🌽", "kukurydza", "corn"],
  ["🎃", "dynia", "pumpkin"],
  ["🥑", "awokado", "avocado"],
  ["🫛", "groch / strąk", "peas / pod"],
  ["🫘", "fasola", "beans"],
  ["🍄", "grzyb", "mushroom"],
  ["🌰", "kasztan", "chestnut"],
  ["🥜", "orzeszki", "peanuts"],
  // owoce
  ["🍓", "truskawka / poziomka", "strawberry"],
  ["🫐", "borówka / jagoda", "blueberry"],
  ["🍇", "winogrona", "grapes"],
  ["rl:raspberry", "malina", "raspberry"],
  ["rl:blackberry", "jeżyna / malinojeżyna", "blackberry"],
  ["rl:gooseberry", "agrest", "gooseberry"],
  ["rl:gooseberry-red", "agrest czerwony", "red gooseberry"],
  ["rl:plum-green", "śliwa zielona / renkloda", "green plum / greengage"],
  ["rl:plum-yellow", "śliwa żółta / mirabelka", "yellow plum / mirabelle"],
  ["rl:plum-purple", "śliwa fioletowa / węgierka", "purple plum"],
  ["rl:plum-red", "śliwa czerwona", "red plum"],
  ["rl:sour-cherry", "wiśnia", "sour cherry"],
  ["rl:grapes-white", "winogrona białe", "white grapes"],
  ["rl:currant-red", "porzeczka czerwona", "redcurrant"],
  ["rl:currant-black", "porzeczka czarna / porzeczkoagrest / aronia", "blackcurrant / jostaberry / chokeberry"],
  ["rl:currant-white", "porzeczka biała", "whitecurrant"],
  ["🍎", "jabłko", "apple"],
  ["🍏", "zielone jabłko", "green apple"],
  ["🍐", "gruszka", "pear"],
  ["🍒", "czereśnia", "sweet cherry"],
  ["🍑", "brzoskwinia", "peach"],
  ["🍋", "cytryna", "lemon"],
  ["🍊", "pomarańcza", "orange"],
  ["🍉", "arbuz", "watermelon"],
  ["🍈", "melon", "melon"],
  ["🥝", "kiwi / agrest", "kiwi / gooseberry"],
  ["🍌", "banan", "banana"],
  ["🍍", "ananas", "pineapple"],
  ["🥭", "mango", "mango"],
  ["🥥", "kokos / orzech", "coconut / nut"],
  ["🫒", "oliwka", "olive"],
  // rośliny, kwiaty, drzewa
  ["🌱", "sadzonka", "seedling"],
  ["🌿", "zioła / krzew", "herb / shrub"],
  ["☘️", "koniczyna", "shamrock"],
  ["🍀", "czterolistna koniczyna", "four leaf clover"],
  ["🌾", "zboże / trawa ozdobna", "sheaf / grain"],
  ["🎋", "bambus", "bamboo"],
  ["🌵", "kaktus / sukulent", "cactus / succulent"],
  ["🌳", "drzewo liściaste", "deciduous tree"],
  ["🌲", "drzewo iglaste / tuja", "evergreen tree / thuja"],
  ["🌴", "palma", "palm tree"],
  ["🍂", "liście jesienne", "fallen leaves"],
  ["🍁", "klon", "maple"],
  ["🍃", "liść na wietrze", "leaf in wind"],
  ["🌷", "tulipan", "tulip"],
  ["🌹", "róża", "rose"],
  ["🥀", "zwiędły kwiat", "wilted flower"],
  ["🌺", "hibiskus", "hibiscus"],
  ["🌸", "kwiat wiśni", "cherry blossom"],
  ["💮", "biały kwiat", "white flower"],
  ["🌼", "stokrotka / rumianek", "daisy / chamomile"],
  ["🌻", "słonecznik", "sunflower"],
  ["🪻", "hiacynt / lawenda", "hyacinth / lavender"],
  ["🪷", "lotos", "lotus"],
  ["💐", "bukiet", "bouquet"],
  ["🪴", "roślina doniczkowa", "potted plant"],
  ["🎍", "dekoracja z bambusa", "pine decoration"],
  ["🪺", "gniazdo z jajkami", "nest with eggs"],
  ["🪹", "puste gniazdo", "empty nest"],
  // zwierzęta i szkodniki
  ["🐛", "gąsienica / szkodnik", "caterpillar / pest"],
  ["🐌", "ślimak", "snail"],
  ["🦋", "motyl", "butterfly"],
  ["🐝", "pszczoła", "bee"],
  ["🐞", "biedronka", "ladybug"],
  ["🪱", "dżdżownica", "worm"],
  ["🕷️", "pająk", "spider"],
  ["🐜", "mrówka", "ant"],
  ["🪲", "chrząszcz", "beetle"],
  ["🦗", "świerszcz / konik polny", "cricket"],
  ["🪰", "mucha", "fly"],
  ["🦟", "komar", "mosquito"],
  ["🐦", "ptak", "bird"],
  ["🐦‍⬛", "kos / kruk", "blackbird / crow"],
  ["🦔", "jeż", "hedgehog"],
  ["🐿️", "wiewiórka", "squirrel"],
  ["🐭", "mysz / gryzoń", "mouse / rodent"],
  ["🦌", "sarna / jeleń", "deer"],
  ["🐇", "królik / zając", "rabbit / hare"],
  ["🐈", "kot", "cat"],
  ["🐕", "pies", "dog"],
  ["🐓", "kura", "chicken"],
  ["🦆", "kaczka", "duck"],
  // pogoda i żywioły
  ["☀️", "słońce", "sun"],
  ["🌤️", "słońce za chmurką", "sun behind cloud"],
  ["⛅", "częściowe zachmurzenie", "partly cloudy"],
  ["☁️", "chmura", "cloud"],
  ["🌧️", "deszcz", "rain"],
  ["⛈️", "burza", "thunderstorm"],
  ["🌩️", "piorun", "lightning"],
  ["🌈", "tęcza", "rainbow"],
  ["❄️", "śnieg / mróz", "snow / frost"],
  ["🧊", "lód / przymrozek", "ice / frost"],
  ["🌫️", "mgła", "fog"],
  ["💨", "wiatr", "wind"],
  ["🌪️", "trąba powietrzna", "tornado"],
  ["🌡️", "termometr", "thermometer"],
  ["💧", "kropla wody", "water drop"],
  ["💦", "krople / zraszanie", "sweat droplets / spray"],
  ["🌊", "woda / fala", "water / wave"],
  ["🔥", "ogień", "fire"],
  ["🌍", "ziemia (planeta)", "earth globe"],
  ["🌙", "księżyc", "moon"],
  ["⭐", "gwiazda", "star"],
  // narzędzia i ogrodnictwo
  ["🧑‍🌾", "ogrodnik", "farmer / gardener"],
  ["🚜", "traktor", "tractor"],
  ["🛠️", "narzędzia", "tools"],
  ["🪓", "siekiera", "axe"],
  ["⛏️", "kilof", "pick"],
  ["🪚", "piła", "saw"],
  ["✂️", "sekator / cięcie", "scissors / pruning"],
  ["🧤", "rękawice", "gloves"],
  ["🧹", "miotła", "broom"],
  ["🪣", "wiadro", "bucket"],
  ["🚿", "prysznic / podlewanie", "shower / watering"],
  ["🧯", "opryskiwacz", "sprayer"],
  ["🧪", "nawóz / oprysk", "fertilizer / test"],
  ["🧫", "rozsada / kiełkowanie", "propagation"],
  ["🧰", "skrzynka narzędziowa", "toolbox"],
  ["📏", "miarka", "ruler"],
  ["🪤", "pułapka", "trap"],
  ["🧲", "magnes", "magnet"],
  ["🪛", "śrubokręt", "screwdriver"],
  ["🔦", "latarka", "flashlight"],
  ["🕸️", "siatka / pajęczyna", "net / web"],
  ["🧵", "sznurek", "thread / twine"],
  ["🎏", "taśmy odstraszające", "streamers"],
  // miejsca i obiekty
  ["🏠", "dom / szklarnia", "house / greenhouse"],
  ["🏡", "dom z ogrodem", "house with garden"],
  ["🛖", "altana / szopa", "hut / shed"],
  ["⛺", "tunel foliowy / namiot", "tent / polytunnel"],
  ["🪟", "inspekt / okno", "window / cold frame"],
  ["🚪", "drzwi", "door"],
  ["🧱", "murek / podwyższona grządka", "bricks / raised bed"],
  ["🪵", "drewno / płot", "wood / fence"],
  ["⛲", "fontanna", "fountain"],
  ["🕳️", "dołek / studnia", "hole / well"],
  ["🗑️", "kosz", "bin"],
  ["♻️", "kompostownik", "compost"],
  ["🛢️", "zbiornik na deszczówkę", "rain barrel"],
  ["🧺", "kosz na zbiory", "harvest basket"],
  ["🛝", "plac zabaw", "playground"],
  ["🏺", "donica", "pot / amphora"],
  ["🔔", "dzwonek", "bell"],
  ["💡", "lampa", "light"],
  ["🔌", "zasilanie", "power"],
  ["📷", "kamera", "camera"],
  ["🧭", "kompas", "compass"],
  ["📍", "pinezka / miejsce", "pin / place"],
  // zioła i przyprawy (symbolicznie)
  ["🫚", "korzeń / burak / rzodkiewka / seler / imbir", "root / beet / radish / celeriac / ginger"],
  ["🍵", "herbata ziołowa / melisa / mięta", "herbal tea / lemon balm / mint"],
  ["🧂", "przyprawy", "spices"],
  ["🍯", "miód", "honey"],
  ["🥗", "sałatka / warzywa liściowe", "salad"],
  ["🥧", "zbiory na przetwory", "harvest pie"],
  ["🫙", "słoik / przetwory", "jar / preserves"],
  // symbole
  ["✅", "gotowe", "done"],
  ["⚠️", "uwaga", "warning"],
  ["❤️", "ulubione", "favorite"],
  ["🎯", "cel", "target"],
  ["📅", "kalendarz", "calendar"],
  ["📝", "notatka", "note"],
  ["🔬", "diagnoza", "diagnosis"],
  ["🧬", "odmiana / genetyka", "variety / genetics"],
  ["🏷️", "etykieta", "label"],
  ["❔", "nieznane", "unknown"],
];

/* Opcje do combo({options}) — wyszukiwanie po nazwie PL i EN, ikona = to samo emoji. */
export const iconOptions = () => C.map(([e, pl, en]) => ({ value: e, label: pl, secondary: en, icon: e }));
