// Presety roślin uprawnych dla polskich ogrodów i szklarni — prefill dla dialogu
// dodawania, edytora i modułu Uprawy. diameter_m/height_m: typowe wymiary dorosłej
// rośliny (plan + cień). Fenologia (warzywa i zioła): family = rodzina botaniczna
// (płodozmian), okna "MM-DD" dla klimatu PL: sow_indoor (siew na rozsadę),
// sow_direct (siew/sadzenie wprost), transplant (wysadzenie), harvest (zbiór),
// spacing_cm (rozstawa w rzędzie). Krzewy/drzewa/żywopłoty — bez fenologii.
export const PLANT_PRESETS = [
  // --- Warzywa ---
  { name: "Pomidor", species: "Solanum lycopersicum", emoji: "🍅", diameter_m: 0.5, height_m: 1.5,
    family: "psiankowate", sow_indoor: ["02-20", "04-10"], sow_direct: null, transplant: ["05-15", "06-10"], harvest: ["07-15", "10-10"], spacing_cm: 50 },
  { name: "Ogórek", species: "Cucumis sativus", emoji: "🥒", diameter_m: 0.6, height_m: 1.8,
    family: "dyniowate", sow_indoor: ["04-10", "05-05"], sow_direct: ["05-15", "06-05"], transplant: ["05-20", "06-10"], harvest: ["07-01", "09-20"], spacing_cm: 30 },
  { name: "Marchew", species: "Daucus carota", emoji: "🥕", diameter_m: 0.1, height_m: 0.3,
    family: "selerowate", sow_indoor: null, sow_direct: ["03-20", "06-30"], transplant: null, harvest: ["06-15", "10-31"], spacing_cm: 5 },
  { name: "Cebula", species: "Allium cepa", emoji: "🧅", diameter_m: 0.1, height_m: 0.4,
    family: "czosnkowate", sow_indoor: null, sow_direct: ["03-25", "04-30"], transplant: null, harvest: ["07-15", "09-15"], spacing_cm: 10 },
  { name: "Cebula siedmiolatka (dymka)", species: "Allium fistulosum", emoji: "🧅", diameter_m: 0.15, height_m: 0.5,
    family: "czosnkowate", sow_indoor: null, sow_direct: ["04-01", "07-31"], transplant: null, harvest: ["05-15", "10-31"], spacing_cm: 15 },
  { name: "Czosnek", species: "Allium sativum", emoji: "🧄", diameter_m: 0.1, height_m: 0.5,
    family: "czosnkowate", sow_indoor: null, sow_direct: ["09-20", "10-31"], transplant: null, harvest: ["06-20", "07-31"], spacing_cm: 15 },
  { name: "Ziemniak", species: "Solanum tuberosum", emoji: "🥔", diameter_m: 0.4, height_m: 0.6,
    family: "psiankowate", sow_indoor: null, sow_direct: ["04-10", "05-15"], transplant: null, harvest: ["07-01", "09-30"], spacing_cm: 35 },
  { name: "Cukinia", species: "Cucurbita pepo", emoji: "🥒", diameter_m: 1.0, height_m: 0.6,
    family: "dyniowate", sow_indoor: ["04-15", "05-05"], sow_direct: ["05-10", "06-05"], transplant: ["05-20", "06-10"], harvest: ["07-01", "09-30"], spacing_cm: 100 },
  { name: "Patison", species: "Cucurbita pepo var. patisson", emoji: "🎃", diameter_m: 0.9, height_m: 0.5,
    family: "dyniowate", sow_indoor: ["04-15", "05-05"], sow_direct: ["05-10", "06-05"], transplant: ["05-20", "06-10"], harvest: ["07-10", "09-30"], spacing_cm: 90 },
  { name: "Dynia", species: "Cucurbita maxima", emoji: "🎃", diameter_m: 2.0, height_m: 0.5,
    family: "dyniowate", sow_indoor: ["04-15", "05-05"], sow_direct: ["05-10", "05-31"], transplant: ["05-20", "06-10"], harvest: ["09-01", "10-15"], spacing_cm: 150 },
  { name: "Dynia piżmowa", species: "Cucurbita moschata", emoji: "🎃", diameter_m: 1.8, height_m: 0.4,
    family: "dyniowate", sow_indoor: ["04-15", "05-05"], sow_direct: ["05-15", "05-31"], transplant: ["05-25", "06-10"], harvest: ["09-15", "10-15"], spacing_cm: 150 },
  { name: "Burak ćwikłowy", species: "Beta vulgaris", emoji: "🫚", diameter_m: 0.15, height_m: 0.35,
    family: "komosowate", sow_indoor: null, sow_direct: ["04-15", "06-30"], transplant: null, harvest: ["07-01", "10-31"], spacing_cm: 10 },
  { name: "Boćwina (burak liściowy)", species: "Beta vulgaris var. cicla", emoji: "🥬", diameter_m: 0.3, height_m: 0.5,
    family: "komosowate", sow_indoor: null, sow_direct: ["04-01", "07-15"], transplant: null, harvest: ["06-01", "10-31"], spacing_cm: 25 },
  { name: "Rzodkiewka", species: "Raphanus sativus", emoji: "🫚", diameter_m: 0.08, height_m: 0.2,
    family: "kapustowate", sow_indoor: null, sow_direct: ["03-15", "09-15"], transplant: null, harvest: ["04-15", "10-15"], spacing_cm: 4 },
  { name: "Papryka", species: "Capsicum annuum", emoji: "🫑", diameter_m: 0.4, height_m: 0.8,
    family: "psiankowate", sow_indoor: ["02-10", "03-20"], sow_direct: null, transplant: ["05-15", "06-10"], harvest: ["07-15", "10-10"], spacing_cm: 40 },
  { name: "Bakłażan (oberżyna)", species: "Solanum melongena", emoji: "🍆", diameter_m: 0.5, height_m: 0.9,
    family: "psiankowate", sow_indoor: ["02-15", "03-20"], sow_direct: null, transplant: ["05-20", "06-10"], harvest: ["08-01", "10-01"], spacing_cm: 50 },
  { name: "Truskawka", species: "Fragaria × ananassa", emoji: "🍓", diameter_m: 0.3, height_m: 0.2,
    family: "różowate", sow_indoor: null, sow_direct: null, transplant: ["08-01", "09-30"], harvest: ["06-01", "07-15"], spacing_cm: 25 },
  { name: "Poziomka ogrodowa", species: "Fragaria vesca", emoji: "🍓", diameter_m: 0.25, height_m: 0.15,
    family: "różowate", sow_indoor: ["03-01", "04-15"], sow_direct: null, transplant: ["05-15", "08-31"], harvest: ["06-01", "09-30"], spacing_cm: 25 },
  { name: "Sałata masłowa", species: "Lactuca sativa var. capitata", emoji: "🥬", diameter_m: 0.3, height_m: 0.25,
    family: "astrowate", sow_indoor: ["02-20", "07-31"], sow_direct: ["04-01", "08-15"], transplant: ["04-15", "08-31"], harvest: ["05-15", "10-15"], spacing_cm: 25 },
  { name: "Sałata lodowa", species: "Lactuca sativa var. capitata (crisphead)", emoji: "🥬", diameter_m: 0.3, height_m: 0.25,
    family: "astrowate", sow_indoor: ["03-01", "06-30"], sow_direct: ["04-15", "07-15"], transplant: ["04-20", "07-31"], harvest: ["06-15", "10-15"], spacing_cm: 30 },
  { name: "Roszponka", species: "Valerianella locusta", emoji: "🥬", diameter_m: 0.1, height_m: 0.1,
    family: "kozłkowate", sow_indoor: null, sow_direct: ["08-01", "09-15"], transplant: null, harvest: ["09-15", "11-30"], spacing_cm: 5 },
  { name: "Rukola", species: "Eruca vesicaria subsp. sativa", emoji: "🌿", diameter_m: 0.15, height_m: 0.25,
    family: "kapustowate", sow_indoor: null, sow_direct: ["03-25", "09-01"], transplant: null, harvest: ["04-20", "10-15"], spacing_cm: 10 },
  { name: "Szpinak", species: "Spinacia oleracea", emoji: "🥬", diameter_m: 0.2, height_m: 0.3,
    family: "komosowate", sow_indoor: null, sow_direct: ["03-15", "04-30"], transplant: null, harvest: ["04-30", "06-15"], spacing_cm: 10 },
  { name: "Koper ogrodowy", species: "Anethum graveolens", emoji: "🌿", diameter_m: 0.15, height_m: 0.6,
    family: "selerowate", sow_indoor: null, sow_direct: ["04-01", "08-15"], transplant: null, harvest: ["05-15", "09-30"], spacing_cm: 5 },
  { name: "Pietruszka korzeniowa", species: "Petroselinum crispum var. tuberosum", emoji: "🥕", diameter_m: 0.15, height_m: 0.35,
    family: "selerowate", sow_indoor: null, sow_direct: ["03-15", "04-30"], transplant: null, harvest: ["09-01", "11-15"], spacing_cm: 8 },
  { name: "Pietruszka naciowa", species: "Petroselinum crispum var. crispum", emoji: "🌿", diameter_m: 0.2, height_m: 0.3,
    family: "selerowate", sow_indoor: null, sow_direct: ["03-15", "07-31"], transplant: null, harvest: ["06-01", "10-31"], spacing_cm: 8 },
  { name: "Szczypiorek", species: "Allium schoenoprasum", emoji: "🌿", diameter_m: 0.2, height_m: 0.35,
    family: "czosnkowate", sow_indoor: null, sow_direct: ["03-20", "05-31"], transplant: null, harvest: ["04-15", "10-31"], spacing_cm: 20 },
  { name: "Fasola szparagowa", species: "Phaseolus vulgaris", emoji: "🫛", diameter_m: 0.3, height_m: 0.5,
    family: "bobowate", sow_indoor: null, sow_direct: ["05-10", "07-10"], transplant: null, harvest: ["07-01", "09-30"], spacing_cm: 10 },
  { name: "Fasola tyczna (na ziarno)", species: "Phaseolus vulgaris / coccineus", emoji: "🫘", diameter_m: 0.3, height_m: 2.2,
    family: "bobowate", sow_indoor: null, sow_direct: ["05-10", "06-10"], transplant: null, harvest: ["08-01", "10-10"], spacing_cm: 20 },
  { name: "Groch siewny", species: "Pisum sativum", emoji: "🫛", diameter_m: 0.2, height_m: 1.2,
    family: "bobowate", sow_indoor: null, sow_direct: ["03-25", "05-15"], transplant: null, harvest: ["06-01", "07-31"], spacing_cm: 6 },
  { name: "Bób", species: "Vicia faba", emoji: "🫘", diameter_m: 0.25, height_m: 1.0,
    family: "bobowate", sow_indoor: null, sow_direct: ["03-15", "04-20"], transplant: null, harvest: ["06-20", "08-15"], spacing_cm: 15 },
  { name: "Por", species: "Allium porrum", emoji: "🧅", diameter_m: 0.1, height_m: 0.5,
    family: "czosnkowate", sow_indoor: ["02-01", "03-15"], sow_direct: null, transplant: ["05-01", "06-15"], harvest: ["09-01", "11-30"], spacing_cm: 15 },
  { name: "Seler korzeniowy", species: "Apium graveolens var. rapaceum", emoji: "🫚", diameter_m: 0.3, height_m: 0.5,
    family: "selerowate", sow_indoor: ["02-01", "03-10"], sow_direct: null, transplant: ["05-10", "06-05"], harvest: ["09-15", "11-15"], spacing_cm: 35 },
  { name: "Seler naciowy", species: "Apium graveolens var. dulce", emoji: "🥬", diameter_m: 0.3, height_m: 0.6,
    family: "selerowate", sow_indoor: ["02-15", "03-20"], sow_direct: null, transplant: ["05-10", "06-05"], harvest: ["08-01", "10-31"], spacing_cm: 30 },
  { name: "Kapusta głowiasta biała", species: "Brassica oleracea var. capitata f. alba", emoji: "🥬", diameter_m: 0.5, height_m: 0.4,
    family: "kapustowate", sow_indoor: ["03-01", "04-15"], sow_direct: null, transplant: ["04-20", "06-15"], harvest: ["08-01", "11-15"], spacing_cm: 50 },
  { name: "Kapusta głowiasta czerwona", species: "Brassica oleracea var. capitata f. rubra", emoji: "🥬", diameter_m: 0.5, height_m: 0.4,
    family: "kapustowate", sow_indoor: ["03-01", "04-15"], sow_direct: null, transplant: ["04-20", "06-15"], harvest: ["08-15", "11-15"], spacing_cm: 50 },
  { name: "Kapusta włoska", species: "Brassica oleracea var. sabauda", emoji: "🥬", diameter_m: 0.5, height_m: 0.4,
    family: "kapustowate", sow_indoor: ["03-01", "04-30"], sow_direct: null, transplant: ["04-20", "06-30"], harvest: ["08-01", "11-30"], spacing_cm: 50 },
  { name: "Kapusta pekińska", species: "Brassica rapa subsp. pekinensis", emoji: "🥬", diameter_m: 0.3, height_m: 0.4,
    family: "kapustowate", sow_indoor: ["06-20", "07-15"], sow_direct: ["07-10", "08-05"], transplant: ["07-15", "08-10"], harvest: ["09-15", "11-15"], spacing_cm: 35 },
  { name: "Brukselka", species: "Brassica oleracea var. gemmifera", emoji: "🥬", diameter_m: 0.4, height_m: 0.9,
    family: "kapustowate", sow_indoor: ["03-15", "04-30"], sow_direct: null, transplant: ["05-15", "06-15"], harvest: ["09-15", "12-15"], spacing_cm: 60 },
  { name: "Kalafior", species: "Brassica oleracea var. botrytis", emoji: "🥦", diameter_m: 0.5, height_m: 0.5,
    family: "kapustowate", sow_indoor: ["03-01", "05-31"], sow_direct: null, transplant: ["04-20", "07-10"], harvest: ["06-15", "10-31"], spacing_cm: 50 },
  { name: "Brokuł", species: "Brassica oleracea var. italica", emoji: "🥦", diameter_m: 0.5, height_m: 0.7,
    family: "kapustowate", sow_indoor: ["03-01", "06-15"], sow_direct: null, transplant: ["04-20", "07-15"], harvest: ["06-15", "10-31"], spacing_cm: 45 },
  { name: "Kalarepa", species: "Brassica oleracea var. gongylodes", emoji: "🥬", diameter_m: 0.25, height_m: 0.35,
    family: "kapustowate", sow_indoor: ["02-20", "06-30"], sow_direct: ["04-15", "07-15"], transplant: ["04-10", "07-31"], harvest: ["05-20", "10-15"], spacing_cm: 25 },
  { name: "Jarmuż", species: "Brassica oleracea var. sabellica", emoji: "🥬", diameter_m: 0.4, height_m: 0.7,
    family: "kapustowate", sow_indoor: ["04-15", "06-15"], sow_direct: ["05-01", "06-30"], transplant: ["06-01", "07-31"], harvest: ["09-01", "12-31"], spacing_cm: 45 },
  { name: "Kukurydza cukrowa", species: "Zea mays var. saccharata", emoji: "🌽", diameter_m: 0.3, height_m: 2.2,
    family: "wiechlinowate", sow_indoor: null, sow_direct: ["05-01", "05-31"], transplant: null, harvest: ["08-01", "09-30"], spacing_cm: 25 },
  { name: "Rabarbar", species: "Rheum rhabarbarum", emoji: "🍃", diameter_m: 0.9, height_m: 0.7,
    family: "rdestowate", sow_indoor: null, sow_direct: null, transplant: ["09-01", "10-31"], harvest: ["04-15", "06-24"], spacing_cm: 100 },
  { name: "Szparag", species: "Asparagus officinalis", emoji: "🌱", diameter_m: 0.4, height_m: 1.5,
    family: "szparagowate", sow_indoor: null, sow_direct: null, transplant: ["03-15", "04-30"], harvest: ["04-20", "06-24"], spacing_cm: 40 },
  { name: "Arbuz (kawon)", species: "Citrullus lanatus", emoji: "🍉", diameter_m: 1.5, height_m: 0.4,
    family: "dyniowate", sow_indoor: ["04-10", "04-30"], sow_direct: null, transplant: ["05-20", "06-10"], harvest: ["08-10", "09-20"], spacing_cm: 100 },
  { name: "Melon", species: "Cucumis melo", emoji: "🍈", diameter_m: 1.2, height_m: 0.4,
    family: "dyniowate", sow_indoor: ["04-10", "04-30"], sow_direct: null, transplant: ["05-20", "06-10"], harvest: ["08-01", "09-30"], spacing_cm: 80 },
  { name: "Chrzan", species: "Armoracia rusticana", emoji: "🌱", diameter_m: 0.5, height_m: 0.8,
    family: "kapustowate", sow_indoor: null, sow_direct: null, transplant: ["03-15", "04-30"], harvest: ["10-15", "11-30"], spacing_cm: 40 },
  { name: "Skorzonera (wężymord)", species: "Scorzonera hispanica", emoji: "🫚", diameter_m: 0.15, height_m: 0.6,
    family: "astrowate", sow_indoor: null, sow_direct: ["04-01", "05-15"], transplant: null, harvest: ["10-01", "11-30"], spacing_cm: 10 },
  { name: "Topinambur", species: "Helianthus tuberosus", emoji: "🌻", diameter_m: 0.5, height_m: 2.5,
    family: "astrowate", sow_indoor: null, sow_direct: ["03-20", "04-30"], transplant: null, harvest: ["10-15", "12-15"], spacing_cm: 40 },
  // --- Zioła ---
  { name: "Bazylia", species: "Ocimum basilicum", emoji: "🌿", diameter_m: 0.25, height_m: 0.4,
    family: "jasnotowate", sow_indoor: ["03-15", "04-30"], sow_direct: ["05-20", "06-15"], transplant: ["05-20", "06-15"], harvest: ["06-15", "09-30"], spacing_cm: 25 },
  { name: "Mięta", species: "Mentha × piperita", emoji: "🌿", diameter_m: 0.4, height_m: 0.5,
    family: "jasnotowate", sow_indoor: null, sow_direct: null, transplant: ["04-15", "06-15"], harvest: ["05-15", "09-30"], spacing_cm: 30 },
  { name: "Tymianek", species: "Thymus vulgaris", emoji: "🌿", diameter_m: 0.25, height_m: 0.25,
    family: "jasnotowate", sow_indoor: ["03-01", "04-15"], sow_direct: ["04-15", "05-31"], transplant: ["05-15", "06-15"], harvest: ["06-01", "09-30"], spacing_cm: 25 },
  { name: "Oregano (lebiodka)", species: "Origanum vulgare", emoji: "🌿", diameter_m: 0.3, height_m: 0.4,
    family: "jasnotowate", sow_indoor: ["03-01", "04-15"], sow_direct: null, transplant: ["05-15", "06-15"], harvest: ["06-15", "09-15"], spacing_cm: 30 },
  { name: "Rozmaryn", species: "Salvia rosmarinus", emoji: "🌿", diameter_m: 0.4, height_m: 0.7,
    family: "jasnotowate", sow_indoor: ["02-15", "03-31"], sow_direct: null, transplant: ["05-20", "06-15"], harvest: ["06-01", "10-15"], spacing_cm: 40 },
  { name: "Szałwia lekarska", species: "Salvia officinalis", emoji: "🌿", diameter_m: 0.4, height_m: 0.6,
    family: "jasnotowate", sow_indoor: ["03-01", "04-15"], sow_direct: ["05-01", "05-31"], transplant: ["05-15", "06-15"], harvest: ["06-01", "09-30"], spacing_cm: 35 },
  { name: "Melisa", species: "Melissa officinalis", emoji: "🌿", diameter_m: 0.4, height_m: 0.6,
    family: "jasnotowate", sow_indoor: ["03-01", "04-15"], sow_direct: null, transplant: ["05-15", "06-15"], harvest: ["06-01", "09-30"], spacing_cm: 35 },
  { name: "Lubczyk", species: "Levisticum officinale", emoji: "🌿", diameter_m: 0.6, height_m: 1.5,
    family: "selerowate", sow_indoor: ["03-01", "04-15"], sow_direct: ["04-15", "05-31"], transplant: ["05-15", "06-30"], harvest: ["05-15", "10-15"], spacing_cm: 50 },
  { name: "Estragon", species: "Artemisia dracunculus", emoji: "🌿", diameter_m: 0.4, height_m: 1.0,
    family: "astrowate", sow_indoor: null, sow_direct: null, transplant: ["04-15", "05-31"], harvest: ["06-01", "09-30"], spacing_cm: 40 },
  { name: "Lawenda", species: "Lavandula angustifolia", emoji: "🪻", diameter_m: 0.5, height_m: 0.6,
    family: "jasnotowate", sow_indoor: null, sow_direct: null, transplant: ["04-15", "05-31"], harvest: ["06-20", "08-15"], spacing_cm: 40 },
  // --- Krzewy i krzewinki owocowe ---
  { name: "Malina", species: "Rubus idaeus", emoji: "rl:raspberry", diameter_m: 0.5, height_m: 1.6 },
  { name: "Porzeczka czarna", species: "Ribes nigrum", emoji: "rl:currant-black", diameter_m: 1.2, height_m: 1.5 },
  { name: "Porzeczka czerwona", species: "Ribes rubrum", emoji: "rl:currant-red", diameter_m: 1.2, height_m: 1.5 },
  { name: "Porzeczka biała", species: "Ribes rubrum (biała)", emoji: "rl:currant-white", diameter_m: 1.2, height_m: 1.5 },
  { name: "Agrest", species: "Ribes uva-crispa", emoji: "rl:gooseberry", diameter_m: 1.0, height_m: 1.2 },
  { name: "Porzeczkoagrest", species: "Ribes × nidigrolaria", emoji: "rl:currant-black", diameter_m: 1.2, height_m: 1.5 },
  { name: "Borówka amerykańska", species: "Vaccinium corymbosum", emoji: "🫐", diameter_m: 1.2, height_m: 1.8 },
  { name: "Borówka brusznica", species: "Vaccinium vitis-idaea", emoji: "🍒", diameter_m: 0.4, height_m: 0.3 },
  { name: "Żurawina wielkoowocowa", species: "Vaccinium macrocarpon", emoji: "🍒", diameter_m: 0.6, height_m: 0.2 },
  { name: "Jeżyna bezkolcowa", species: "Rubus fruticosus", emoji: "rl:blackberry", diameter_m: 1.0, height_m: 1.8 },
  { name: "Malinojeżyna", species: "Rubus × loganobaccus", emoji: "rl:blackberry", diameter_m: 1.0, height_m: 1.8 },
  { name: "Malinotruskawka", species: "Rubus illecebrosus", emoji: "🍓", diameter_m: 0.6, height_m: 0.6 },
  { name: "Jagoda kamczacka", species: "Lonicera caerulea var. kamtschatica", emoji: "🫐", diameter_m: 1.2, height_m: 1.5 },
  { name: "Aronia czarnoowocowa", species: "Aronia melanocarpa", emoji: "🫐", diameter_m: 1.8, height_m: 2.0 },
  { name: "Aronia śliwolistna", species: "Aronia × prunifolia", emoji: "🫐", diameter_m: 1.8, height_m: 2.0 },
  { name: "Pigwowiec japoński", species: "Chaenomeles japonica", emoji: "🍋", diameter_m: 1.0, height_m: 1.0 },
  { name: "Pigwowiec pośredni", species: "Chaenomeles × superba", emoji: "🍋", diameter_m: 1.2, height_m: 1.2 },
  { name: "Dereń jadalny", species: "Cornus mas", emoji: "🍒", diameter_m: 3.0, height_m: 3.5 },
  { name: "Rokitnik", species: "Hippophae rhamnoides", emoji: "🍊", diameter_m: 2.5, height_m: 3.0 },
  { name: "Świdośliwa olcholistna", species: "Amelanchier alnifolia", emoji: "🫐", diameter_m: 2.5, height_m: 3.0 },
  { name: "Jagoda goji (kolcowój)", species: "Lycium barbarum", emoji: "🍒", diameter_m: 1.5, height_m: 2.0 },
  { name: "Leszczyna pospolita", species: "Corylus avellana", emoji: "🌰", diameter_m: 3.0, height_m: 3.5 },
  { name: "Czarny bez", species: "Sambucus nigra", emoji: "🫐", diameter_m: 3.0, height_m: 3.5 },
  { name: "Winorośl", species: "Vitis vinifera", emoji: "🍇", diameter_m: 1.5, height_m: 2.5 },
  { name: "Aktinidia (mini kiwi)", species: "Actinidia arguta", emoji: "🥝", diameter_m: 1.5, height_m: 3.0 },
  { name: "Cytryniec chiński", species: "Schisandra chinensis", emoji: "🍒", diameter_m: 1.0, height_m: 3.0 },
  { name: "Róża pomarszczona", species: "Rosa rugosa", emoji: "🌹", diameter_m: 1.5, height_m: 1.5 },
  { name: "Róża dzika wielkoowocowa", species: "Rosa canina", emoji: "🌹", diameter_m: 2.0, height_m: 2.5 },
  { name: "Oliwnik baldaszkowaty", species: "Elaeagnus umbellata", emoji: "🫒", diameter_m: 3.0, height_m: 3.5 },
  { name: "Morwa czarna (krzew)", species: "Morus nigra", emoji: "🫐", diameter_m: 3.0, height_m: 3.0 },
  // --- Drzewa owocowe i orzechodajne ---
  { name: "Jabłoń", species: "Malus domestica", emoji: "🍎", diameter_m: 4.0, height_m: 4.5 },
  { name: "Grusza", species: "Pyrus communis", emoji: "🍐", diameter_m: 3.5, height_m: 5.0 },
  { name: "Czereśnia", species: "Prunus avium", emoji: "🍒", diameter_m: 4.5, height_m: 6.0 },
  { name: "Wiśnia", species: "Prunus cerasus", emoji: "rl:sour-cherry", diameter_m: 3.0, height_m: 3.5 },
  { name: "Śliwa domowa (węgierka)", species: "Prunus domestica", emoji: "rl:plum-purple", diameter_m: 3.5, height_m: 4.0 },
  { name: "Śliwa lubaszka", species: "Prunus domestica subsp. insititia", emoji: "rl:plum-purple", diameter_m: 3.0, height_m: 3.5 },
  { name: "Śliwa japońska", species: "Prunus salicina", emoji: "rl:plum-red", diameter_m: 3.0, height_m: 3.5 },
  { name: "Mirabelka (ałycza)", species: "Prunus cerasifera", emoji: "rl:plum-yellow", diameter_m: 3.5, height_m: 4.5 },
  { name: "Brzoskwinia", species: "Prunus persica", emoji: "🍑", diameter_m: 3.0, height_m: 3.5 },
  { name: "Nektarynka", species: "Prunus persica var. nucipersica", emoji: "🍑", diameter_m: 3.0, height_m: 3.5 },
  { name: "Morela", species: "Prunus armeniaca", emoji: "🍑", diameter_m: 3.5, height_m: 4.0 },
  { name: "Orzech włoski", species: "Juglans regia", emoji: "🌰", diameter_m: 8.0, height_m: 12.0 },
  { name: "Orzech czarny", species: "Juglans nigra", emoji: "🌰", diameter_m: 9.0, height_m: 14.0 },
  { name: "Orzech szary", species: "Juglans cinerea", emoji: "🌰", diameter_m: 8.0, height_m: 12.0 },
  { name: "Leszczyna turecka (drzewo)", species: "Corylus colurna", emoji: "🌰", diameter_m: 6.0, height_m: 10.0 },
  { name: "Kasztan jadalny", species: "Castanea sativa", emoji: "🌰", diameter_m: 8.0, height_m: 12.0 },
  { name: "Migdałowiec", species: "Prunus dulcis", emoji: "🌰", diameter_m: 3.5, height_m: 4.0 },
  { name: "Pigwa pospolita", species: "Cydonia oblonga", emoji: "🍋", diameter_m: 3.0, height_m: 4.0 },
  { name: "Morwa biała", species: "Morus alba", emoji: "🍇", diameter_m: 5.0, height_m: 8.0 },
  { name: "Morwa czarna (drzewo)", species: "Morus nigra", emoji: "🫐", diameter_m: 5.0, height_m: 7.0 },
  { name: "Świdośliwa Lamarcka", species: "Amelanchier lamarckii", emoji: "🫐", diameter_m: 4.0, height_m: 5.0 },
  { name: "Dereń jadalny (na pniu)", species: "Cornus mas", emoji: "🍒", diameter_m: 3.5, height_m: 4.5 },
  { name: "Jarząb pospolity 'Edulis'", species: "Sorbus aucuparia 'Edulis'", emoji: "🍊", diameter_m: 4.0, height_m: 8.0 },
  { name: "Jarząb domowy", species: "Sorbus domestica", emoji: "🍐", diameter_m: 5.0, height_m: 9.0 },
  { name: "Nieszpułka", species: "Mespilus germanica", emoji: "🍈", diameter_m: 3.5, height_m: 4.0 },
  { name: "Głóg wielkoowocowy", species: "Crataegus monogyna / laevigata", emoji: "🍒", diameter_m: 4.0, height_m: 5.0 },
  { name: "Czeremcha amerykańska", species: "Prunus serotina", emoji: "🍒", diameter_m: 5.0, height_m: 8.0 },
  { name: "Asymina (banan preriowy)", species: "Asimina triloba", emoji: "🍌", diameter_m: 3.0, height_m: 4.0 },
  { name: "Hurma (kaki)", species: "Diospyros kaki / virginiana", emoji: "🍊", diameter_m: 3.5, height_m: 4.5 },
  { name: "Figowiec", species: "Ficus carica", emoji: "🍈", diameter_m: 2.5, height_m: 3.0 },
  // --- Żywopłoty i ogrodzenia ---
  { name: "Tuja (żywotnik zachodni)", species: "Thuja occidentalis ('Brabant'/'Smaragd')", emoji: "🌲", diameter_m: 1.2, height_m: 3.5 },
  { name: "Żywotnik olbrzymi", species: "Thuja plicata", emoji: "🌲", diameter_m: 1.5, height_m: 5.0 },
  { name: "Bukszpan", species: "Buxus sempervirens", emoji: "🌳", diameter_m: 0.8, height_m: 1.0 },
  { name: "Cis pospolity", species: "Taxus baccata", emoji: "🌲", diameter_m: 1.5, height_m: 2.5 },
  { name: "Cyprysik Lawsona", species: "Chamaecyparis lawsoniana", emoji: "🌲", diameter_m: 1.2, height_m: 4.0 },
  { name: "Jałowiec pospolity", species: "Juniperus communis", emoji: "🌲", diameter_m: 1.0, height_m: 2.5 },
  { name: "Świerk pospolity (żywopłot)", species: "Picea abies", emoji: "🌲", diameter_m: 1.5, height_m: 3.0 },
  { name: "Ligustr pospolity", species: "Ligustrum vulgare", emoji: "🌳", diameter_m: 1.0, height_m: 2.0 },
  { name: "Grab pospolity (żywopłot)", species: "Carpinus betulus", emoji: "🌳", diameter_m: 1.2, height_m: 3.0 },
  { name: "Laurowiśnia wschodnia", species: "Prunus laurocerasus", emoji: "🌳", diameter_m: 1.5, height_m: 2.5 },
  { name: "Berberys Thunberga", species: "Berberis thunbergii", emoji: "🍁", diameter_m: 1.2, height_m: 1.2 },
  { name: "Ognik szkarłatny", species: "Pyracantha coccinea", emoji: "🍒", diameter_m: 1.5, height_m: 2.5 },
  { name: "Irga błyszcząca", species: "Cotoneaster lucidus", emoji: "🌳", diameter_m: 1.2, height_m: 2.0 },
  { name: "Pęcherznica kalinolistna", species: "Physocarpus opulifolius", emoji: "🍁", diameter_m: 1.8, height_m: 2.5 },
  { name: "Dereń biały", species: "Cornus alba", emoji: "🌳", diameter_m: 2.0, height_m: 2.5 },
  { name: "Forsycja pośrednia", species: "Forsythia × intermedia", emoji: "🌼", diameter_m: 2.0, height_m: 2.5 },
  { name: "Tawuła szara", species: "Spiraea × cinerea 'Grefsheim'", emoji: "🌼", diameter_m: 1.5, height_m: 1.8 },
  { name: "Hortensja bukietowa", species: "Hydrangea paniculata", emoji: "💐", diameter_m: 1.5, height_m: 2.0 },
];
