// Presety roślin uprawnych dla polskich ogrodów i szklarni — prefill dla dialogu
// dodawania i edytora. diameter_m/height_m: typowe wymiary dorosłej rośliny (plan + cień).
export const PLANT_PRESETS = [
  // --- Warzywa ---
  { name: "Pomidor", species: "Solanum lycopersicum", emoji: "🍅", diameter_m: 0.5, height_m: 1.5 },
  { name: "Ogórek", species: "Cucumis sativus", emoji: "🥒", diameter_m: 0.6, height_m: 1.8 },
  { name: "Marchew", species: "Daucus carota", emoji: "🥕", diameter_m: 0.1, height_m: 0.3 },
  { name: "Cebula", species: "Allium cepa", emoji: "🧅", diameter_m: 0.1, height_m: 0.4 },
  { name: "Cebula siedmiolatka (dymka)", species: "Allium fistulosum", emoji: "🧅", diameter_m: 0.15, height_m: 0.5 },
  { name: "Czosnek", species: "Allium sativum", emoji: "🧄", diameter_m: 0.1, height_m: 0.5 },
  { name: "Ziemniak", species: "Solanum tuberosum", emoji: "🥔", diameter_m: 0.4, height_m: 0.6 },
  { name: "Cukinia", species: "Cucurbita pepo", emoji: "🥒", diameter_m: 1.0, height_m: 0.6 },
  { name: "Patison", species: "Cucurbita pepo var. patisson", emoji: "🎃", diameter_m: 0.9, height_m: 0.5 },
  { name: "Dynia", species: "Cucurbita maxima", emoji: "🎃", diameter_m: 2.0, height_m: 0.5 },
  { name: "Dynia piżmowa", species: "Cucurbita moschata", emoji: "🎃", diameter_m: 1.8, height_m: 0.4 },
  { name: "Burak ćwikłowy", species: "Beta vulgaris", emoji: "🫜", diameter_m: 0.15, height_m: 0.35 },
  { name: "Boćwina (burak liściowy)", species: "Beta vulgaris var. cicla", emoji: "🥬", diameter_m: 0.3, height_m: 0.5 },
  { name: "Rzodkiewka", species: "Raphanus sativus", emoji: "🫜", diameter_m: 0.08, height_m: 0.2 },
  { name: "Papryka", species: "Capsicum annuum", emoji: "🫑", diameter_m: 0.4, height_m: 0.8 },
  { name: "Bakłażan (oberżyna)", species: "Solanum melongena", emoji: "🍆", diameter_m: 0.5, height_m: 0.9 },
  { name: "Truskawka", species: "Fragaria × ananassa", emoji: "🍓", diameter_m: 0.3, height_m: 0.2 },
  { name: "Poziomka ogrodowa", species: "Fragaria vesca", emoji: "🍓", diameter_m: 0.25, height_m: 0.15 },
  { name: "Sałata masłowa", species: "Lactuca sativa var. capitata", emoji: "🥬", diameter_m: 0.3, height_m: 0.25 },
  { name: "Sałata lodowa", species: "Lactuca sativa var. capitata (crisphead)", emoji: "🥬", diameter_m: 0.3, height_m: 0.25 },
  { name: "Roszponka", species: "Valerianella locusta", emoji: "🥬", diameter_m: 0.1, height_m: 0.1 },
  { name: "Rukola", species: "Eruca vesicaria subsp. sativa", emoji: "🌿", diameter_m: 0.15, height_m: 0.25 },
  { name: "Szpinak", species: "Spinacia oleracea", emoji: "🥬", diameter_m: 0.2, height_m: 0.3 },
  { name: "Koper ogrodowy", species: "Anethum graveolens", emoji: "🌿", diameter_m: 0.15, height_m: 0.6 },
  { name: "Pietruszka korzeniowa", species: "Petroselinum crispum var. tuberosum", emoji: "🥕", diameter_m: 0.15, height_m: 0.35 },
  { name: "Pietruszka naciowa", species: "Petroselinum crispum var. crispum", emoji: "🌿", diameter_m: 0.2, height_m: 0.3 },
  { name: "Szczypiorek", species: "Allium schoenoprasum", emoji: "🌿", diameter_m: 0.2, height_m: 0.35 },
  { name: "Fasola szparagowa", species: "Phaseolus vulgaris", emoji: "🫛", diameter_m: 0.3, height_m: 0.5 },
  { name: "Fasola tyczna (na ziarno)", species: "Phaseolus vulgaris / coccineus", emoji: "🫘", diameter_m: 0.3, height_m: 2.2 },
  { name: "Groch siewny", species: "Pisum sativum", emoji: "🫛", diameter_m: 0.2, height_m: 1.2 },
  { name: "Bób", species: "Vicia faba", emoji: "🫘", diameter_m: 0.25, height_m: 1.0 },
  { name: "Por", species: "Allium porrum", emoji: "🧅", diameter_m: 0.1, height_m: 0.5 },
  { name: "Seler korzeniowy", species: "Apium graveolens var. rapaceum", emoji: "🫜", diameter_m: 0.3, height_m: 0.5 },
  { name: "Seler naciowy", species: "Apium graveolens var. dulce", emoji: "🥬", diameter_m: 0.3, height_m: 0.6 },
  { name: "Kapusta głowiasta biała", species: "Brassica oleracea var. capitata f. alba", emoji: "🥬", diameter_m: 0.5, height_m: 0.4 },
  { name: "Kapusta głowiasta czerwona", species: "Brassica oleracea var. capitata f. rubra", emoji: "🥬", diameter_m: 0.5, height_m: 0.4 },
  { name: "Kapusta włoska", species: "Brassica oleracea var. sabauda", emoji: "🥬", diameter_m: 0.5, height_m: 0.4 },
  { name: "Kapusta pekińska", species: "Brassica rapa subsp. pekinensis", emoji: "🥬", diameter_m: 0.3, height_m: 0.4 },
  { name: "Brukselka", species: "Brassica oleracea var. gemmifera", emoji: "🥬", diameter_m: 0.4, height_m: 0.9 },
  { name: "Kalafior", species: "Brassica oleracea var. botrytis", emoji: "🥦", diameter_m: 0.5, height_m: 0.5 },
  { name: "Brokuł", species: "Brassica oleracea var. italica", emoji: "🥦", diameter_m: 0.5, height_m: 0.7 },
  { name: "Kalarepa", species: "Brassica oleracea var. gongylodes", emoji: "🥬", diameter_m: 0.25, height_m: 0.35 },
  { name: "Jarmuż", species: "Brassica oleracea var. sabellica", emoji: "🥬", diameter_m: 0.4, height_m: 0.7 },
  { name: "Kukurydza cukrowa", species: "Zea mays var. saccharata", emoji: "🌽", diameter_m: 0.3, height_m: 2.2 },
  { name: "Rabarbar", species: "Rheum rhabarbarum", emoji: "🍃", diameter_m: 0.9, height_m: 0.7 },
  { name: "Szparag", species: "Asparagus officinalis", emoji: "🌱", diameter_m: 0.4, height_m: 1.5 },
  { name: "Arbuz (kawon)", species: "Citrullus lanatus", emoji: "🍉", diameter_m: 1.5, height_m: 0.4 },
  { name: "Melon", species: "Cucumis melo", emoji: "🍈", diameter_m: 1.2, height_m: 0.4 },
  { name: "Chrzan", species: "Armoracia rusticana", emoji: "🌱", diameter_m: 0.5, height_m: 0.8 },
  { name: "Skorzonera (wężymord)", species: "Scorzonera hispanica", emoji: "🫜", diameter_m: 0.15, height_m: 0.6 },
  { name: "Topinambur", species: "Helianthus tuberosus", emoji: "🌻", diameter_m: 0.5, height_m: 2.5 },
  // --- Zioła ---
  { name: "Bazylia", species: "Ocimum basilicum", emoji: "🌿", diameter_m: 0.25, height_m: 0.4 },
  { name: "Mięta", species: "Mentha × piperita", emoji: "🌿", diameter_m: 0.4, height_m: 0.5 },
  { name: "Tymianek", species: "Thymus vulgaris", emoji: "🌿", diameter_m: 0.25, height_m: 0.25 },
  { name: "Oregano (lebiodka)", species: "Origanum vulgare", emoji: "🌿", diameter_m: 0.3, height_m: 0.4 },
  { name: "Rozmaryn", species: "Salvia rosmarinus", emoji: "🌿", diameter_m: 0.4, height_m: 0.7 },
  { name: "Szałwia lekarska", species: "Salvia officinalis", emoji: "🌿", diameter_m: 0.4, height_m: 0.6 },
  { name: "Melisa", species: "Melissa officinalis", emoji: "🌿", diameter_m: 0.4, height_m: 0.6 },
  { name: "Lubczyk", species: "Levisticum officinale", emoji: "🌿", diameter_m: 0.6, height_m: 1.5 },
  { name: "Estragon", species: "Artemisia dracunculus", emoji: "🌿", diameter_m: 0.4, height_m: 1.0 },
  { name: "Lawenda", species: "Lavandula angustifolia", emoji: "🪻", diameter_m: 0.5, height_m: 0.6 },
  // --- Krzewy i krzewinki owocowe ---
  { name: "Malina", species: "Rubus idaeus", emoji: "🍇", diameter_m: 0.5, height_m: 1.6 },
  { name: "Porzeczka czarna", species: "Ribes nigrum", emoji: "🫐", diameter_m: 1.2, height_m: 1.5 },
  { name: "Porzeczka czerwona", species: "Ribes rubrum", emoji: "🍒", diameter_m: 1.2, height_m: 1.5 },
  { name: "Porzeczka biała", species: "Ribes rubrum (biała)", emoji: "🍇", diameter_m: 1.2, height_m: 1.5 },
  { name: "Agrest", species: "Ribes uva-crispa", emoji: "🍈", diameter_m: 1.0, height_m: 1.2 },
  { name: "Porzeczkoagrest", species: "Ribes × nidigrolaria", emoji: "🍇", diameter_m: 1.2, height_m: 1.5 },
  { name: "Borówka amerykańska", species: "Vaccinium corymbosum", emoji: "🫐", diameter_m: 1.2, height_m: 1.8 },
  { name: "Borówka brusznica", species: "Vaccinium vitis-idaea", emoji: "🍒", diameter_m: 0.4, height_m: 0.3 },
  { name: "Żurawina wielkoowocowa", species: "Vaccinium macrocarpon", emoji: "🍒", diameter_m: 0.6, height_m: 0.2 },
  { name: "Jeżyna bezkolcowa", species: "Rubus fruticosus", emoji: "🫐", diameter_m: 1.0, height_m: 1.8 },
  { name: "Malinojeżyna", species: "Rubus × loganobaccus", emoji: "🍇", diameter_m: 1.0, height_m: 1.8 },
  { name: "Malinotruskawka", species: "Rubus illecebrosus", emoji: "🍓", diameter_m: 0.6, height_m: 0.6 },
  { name: "Jagoda kamczacka", species: "Lonicera caerulea var. kamtschatica", emoji: "🫐", diameter_m: 1.2, height_m: 1.5 },
  { name: "Aronia czarnoowocowa", species: "Aronia melanocarpa", emoji: "🫐", diameter_m: 1.8, height_m: 2.0 },
  { name: "Aronia śliwolistna", species: "Aronia × prunifolia", emoji: "🫐", diameter_m: 1.8, height_m: 2.0 },
  { name: "Pigwowiec japoński", species: "Chaenomeles japonica", emoji: "🍋", diameter_m: 1.0, height_m: 1.0 },
  { name: "Pigwowiec pośredni", species: "Chaenomeles × superba", emoji: "🍋", diameter_m: 1.2, height_m: 1.2 },
  { name: "Dereń jadalny", species: "Cornus mas", emoji: "🍒", diameter_m: 3.0, height_m: 3.5 },
  { name: "Rokitnik", species: "Hippophae rhamnoides", emoji: "🍊", diameter_m: 2.5, height_m: 3.0 },
  { name: "Świdośliwa olcholistna", species: "Amelanchier alnifolia", emoji: "🫐", diameter_m: 2.5, height_m: 3.0 },
  { name: "Jagoda goji (kolcowój)", species: "Lycium barbarum", emoji: "🍒", diameter_m: 1.5, height_m: 2.0 },
  { name: "Leszczyna pospolita", species: "Corylus avellana", emoji: "🌰", diameter_m: 3.0, height_m: 3.5 },
  { name: "Czarny bez", species: "Sambucus nigra", emoji: "🫐", diameter_m: 3.0, height_m: 3.5 },
  { name: "Winorośl", species: "Vitis vinifera", emoji: "🍇", diameter_m: 1.5, height_m: 2.5 },
  { name: "Aktinidia (mini kiwi)", species: "Actinidia arguta", emoji: "🥝", diameter_m: 1.5, height_m: 3.0 },
  { name: "Cytryniec chiński", species: "Schisandra chinensis", emoji: "🍒", diameter_m: 1.0, height_m: 3.0 },
  { name: "Róża pomarszczona", species: "Rosa rugosa", emoji: "🌹", diameter_m: 1.5, height_m: 1.5 },
  { name: "Róża dzika wielkoowocowa", species: "Rosa canina", emoji: "🌹", diameter_m: 2.0, height_m: 2.5 },
  { name: "Oliwnik baldaszkowaty", species: "Elaeagnus umbellata", emoji: "🫒", diameter_m: 3.0, height_m: 3.5 },
  { name: "Morwa czarna (krzew)", species: "Morus nigra", emoji: "🫐", diameter_m: 3.0, height_m: 3.0 },
  // --- Drzewa owocowe i orzechodajne ---
  { name: "Jabłoń", species: "Malus domestica", emoji: "🍎", diameter_m: 4.0, height_m: 4.5 },
  { name: "Grusza", species: "Pyrus communis", emoji: "🍐", diameter_m: 3.5, height_m: 5.0 },
  { name: "Czereśnia", species: "Prunus avium", emoji: "🍒", diameter_m: 4.5, height_m: 6.0 },
  { name: "Wiśnia", species: "Prunus cerasus", emoji: "🍒", diameter_m: 3.0, height_m: 3.5 },
  { name: "Śliwa domowa (węgierka)", species: "Prunus domestica", emoji: "🍑", diameter_m: 3.5, height_m: 4.0 },
  { name: "Śliwa lubaszka", species: "Prunus domestica subsp. insititia", emoji: "🍑", diameter_m: 3.0, height_m: 3.5 },
  { name: "Śliwa japońska", species: "Prunus salicina", emoji: "🍑", diameter_m: 3.0, height_m: 3.5 },
  { name: "Mirabelka (ałycza)", species: "Prunus cerasifera", emoji: "🍑", diameter_m: 3.5, height_m: 4.5 },
  { name: "Brzoskwinia", species: "Prunus persica", emoji: "🍑", diameter_m: 3.0, height_m: 3.5 },
  { name: "Nektarynka", species: "Prunus persica var. nucipersica", emoji: "🍑", diameter_m: 3.0, height_m: 3.5 },
  { name: "Morela", species: "Prunus armeniaca", emoji: "🍑", diameter_m: 3.5, height_m: 4.0 },
  { name: "Orzech włoski", species: "Juglans regia", emoji: "🌰", diameter_m: 8.0, height_m: 12.0 },
  { name: "Orzech czarny", species: "Juglans nigra", emoji: "🌰", diameter_m: 9.0, height_m: 14.0 },
  { name: "Orzech szary", species: "Juglans cinerea", emoji: "🌰", diameter_m: 8.0, height_m: 12.0 },
  { name: "Leszczyna turecka (drzewo)", species: "Corylus colurna", emoji: "🌰", diameter_m: 6.0, height_m: 10.0 },
  { name: "Kasztan jadalny", species: "Castanea sativa", emoji: "🌰", diameter_m: 8.0, height_m: 12.0 },
  { name: "Migdałowiec", species: "Prunus dulcis", emoji: "🌰", diameter_m: 3.5, height_m: 4.0 },
  { name: "Pigwa pospolita", species: "Cydonia oblonga", emoji: "🍋", diameter_m: 3.0, height_m: 4.0 },
  { name: "Morwa biała", species: "Morus alba", emoji: "🍇", diameter_m: 5.0, height_m: 8.0 },
  { name: "Morwa czarna (drzewo)", species: "Morus nigra", emoji: "🫐", diameter_m: 5.0, height_m: 7.0 },
  { name: "Świdośliwa Lamarcka", species: "Amelanchier lamarckii", emoji: "🫐", diameter_m: 4.0, height_m: 5.0 },
  { name: "Dereń jadalny (na pniu)", species: "Cornus mas", emoji: "🍒", diameter_m: 3.5, height_m: 4.5 },
  { name: "Jarząb pospolity 'Edulis'", species: "Sorbus aucuparia 'Edulis'", emoji: "🍊", diameter_m: 4.0, height_m: 8.0 },
  { name: "Jarząb domowy", species: "Sorbus domestica", emoji: "🍐", diameter_m: 5.0, height_m: 9.0 },
  { name: "Nieszpułka", species: "Mespilus germanica", emoji: "🍈", diameter_m: 3.5, height_m: 4.0 },
  { name: "Głóg wielkoowocowy", species: "Crataegus monogyna / laevigata", emoji: "🍒", diameter_m: 4.0, height_m: 5.0 },
  { name: "Czeremcha amerykańska", species: "Prunus serotina", emoji: "🍒", diameter_m: 5.0, height_m: 8.0 },
  { name: "Asymina (banan preriowy)", species: "Asimina triloba", emoji: "🍌", diameter_m: 3.0, height_m: 4.0 },
  { name: "Hurma (kaki)", species: "Diospyros kaki / virginiana", emoji: "🍊", diameter_m: 3.5, height_m: 4.5 },
  { name: "Figowiec", species: "Ficus carica", emoji: "🍈", diameter_m: 2.5, height_m: 3.0 },
  // --- Żywopłoty i ogrodzenia ---
  { name: "Tuja (żywotnik zachodni)", species: "Thuja occidentalis ('Brabant'/'Smaragd')", emoji: "🌲", diameter_m: 1.2, height_m: 3.5 },
  { name: "Żywotnik olbrzymi", species: "Thuja plicata", emoji: "🌲", diameter_m: 1.5, height_m: 5.0 },
  { name: "Bukszpan", species: "Buxus sempervirens", emoji: "🌳", diameter_m: 0.8, height_m: 1.0 },
  { name: "Cis pospolity", species: "Taxus baccata", emoji: "🌲", diameter_m: 1.5, height_m: 2.5 },
  { name: "Cyprysik Lawsona", species: "Chamaecyparis lawsoniana", emoji: "🌲", diameter_m: 1.2, height_m: 4.0 },
  { name: "Jałowiec pospolity", species: "Juniperus communis", emoji: "🌲", diameter_m: 1.0, height_m: 2.5 },
  { name: "Świerk pospolity (żywopłot)", species: "Picea abies", emoji: "🌲", diameter_m: 1.5, height_m: 3.0 },
  { name: "Ligustr pospolity", species: "Ligustrum vulgare", emoji: "🌳", diameter_m: 1.0, height_m: 2.0 },
  { name: "Grab pospolity (żywopłot)", species: "Carpinus betulus", emoji: "🌳", diameter_m: 1.2, height_m: 3.0 },
  { name: "Laurowiśnia wschodnia", species: "Prunus laurocerasus", emoji: "🌳", diameter_m: 1.5, height_m: 2.5 },
  { name: "Berberys Thunberga", species: "Berberis thunbergii", emoji: "🍁", diameter_m: 1.2, height_m: 1.2 },
  { name: "Ognik szkarłatny", species: "Pyracantha coccinea", emoji: "🍒", diameter_m: 1.5, height_m: 2.5 },
  { name: "Irga błyszcząca", species: "Cotoneaster lucidus", emoji: "🌳", diameter_m: 1.2, height_m: 2.0 },
  { name: "Pęcherznica kalinolistna", species: "Physocarpus opulifolius", emoji: "🍁", diameter_m: 1.8, height_m: 2.5 },
  { name: "Dereń biały", species: "Cornus alba", emoji: "🌳", diameter_m: 2.0, height_m: 2.5 },
  { name: "Forsycja pośrednia", species: "Forsythia × intermedia", emoji: "🌼", diameter_m: 2.0, height_m: 2.5 },
  { name: "Tawuła szara", species: "Spiraea × cinerea 'Grefsheim'", emoji: "🌼", diameter_m: 1.5, height_m: 1.8 },
  { name: "Hortensja bukietowa", species: "Hydrangea paniculata", emoji: "💐", diameter_m: 1.5, height_m: 2.0 },
];
