// 25 popularnych roślin ogrodowych — prefill dla dialogu dodawania i edytora.
export const PLANT_PRESETS = [
  { name: "Pomidor", species: "Solanum lycopersicum", emoji: "🍅", diameter_m: 0.5, height_m: 1.5 },
  { name: "Ogórek", species: "Cucumis sativus", emoji: "🥒", diameter_m: 0.6, height_m: 1.8 },
  { name: "Papryka", species: "Capsicum annuum", emoji: "🫑", diameter_m: 0.4, height_m: 0.8 },
  { name: "Sałata", species: "Lactuca sativa", emoji: "🥬", diameter_m: 0.3, height_m: 0.25 },
  { name: "Marchew", species: "Daucus carota", emoji: "🥕", diameter_m: 0.1, height_m: 0.3 },
  { name: "Ziemniak", species: "Solanum tuberosum", emoji: "🥔", diameter_m: 0.4, height_m: 0.6 },
  { name: "Cebula", species: "Allium cepa", emoji: "🧅", diameter_m: 0.1, height_m: 0.4 },
  { name: "Czosnek", species: "Allium sativum", emoji: "🧄", diameter_m: 0.1, height_m: 0.5 },
  { name: "Cukinia", species: "Cucurbita pepo", emoji: "🥒", diameter_m: 1.0, height_m: 0.6 },
  { name: "Dynia", species: "Cucurbita maxima", emoji: "🎃", diameter_m: 2.0, height_m: 0.5 },
  { name: "Truskawka", species: "Fragaria × ananassa", emoji: "🍓", diameter_m: 0.3, height_m: 0.2 },
  { name: "Malina", species: "Rubus idaeus", emoji: "🍇", diameter_m: 0.5, height_m: 1.6 },
  { name: "Porzeczka czarna", species: "Ribes nigrum", emoji: "🫐", diameter_m: 1.2, height_m: 1.5 },
  { name: "Borówka amerykańska", species: "Vaccinium corymbosum", emoji: "🫐", diameter_m: 1.2, height_m: 1.8 },
  { name: "Agrest", species: "Ribes uva-crispa", emoji: "🍈", diameter_m: 1.0, height_m: 1.2 },
  { name: "Jabłoń", species: "Malus domestica", emoji: "🍎", diameter_m: 4.0, height_m: 4.5 },
  { name: "Grusza", species: "Pyrus communis", emoji: "🍐", diameter_m: 3.5, height_m: 5.0 },
  { name: "Śliwa", species: "Prunus domestica", emoji: "🍑", diameter_m: 3.5, height_m: 4.0 },
  { name: "Wiśnia", species: "Prunus cerasus", emoji: "🍒", diameter_m: 3.0, height_m: 3.5 },
  { name: "Bazylia", species: "Ocimum basilicum", emoji: "🌿", diameter_m: 0.25, height_m: 0.4 },
  { name: "Mięta", species: "Mentha × piperita", emoji: "🌿", diameter_m: 0.4, height_m: 0.5 },
  { name: "Pietruszka", species: "Petroselinum crispum", emoji: "🌿", diameter_m: 0.2, height_m: 0.3 },
  { name: "Koperek", species: "Anethum graveolens", emoji: "🌿", diameter_m: 0.15, height_m: 0.6 },
  { name: "Szczypiorek", species: "Allium schoenoprasum", emoji: "🌿", diameter_m: 0.2, height_m: 0.35 },
  { name: "Rzodkiewka", species: "Raphanus sativus", emoji: "🌶️", diameter_m: 0.08, height_m: 0.2 },
];
